# Generated by Django 2.2 on 2019-04-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
