# Generated by Django 2.2 on 2019-04-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0003_recipe_recipeingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipeIngredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='WorkbenchApp.Recipe'),
            preserve_default=False,
        ),
    ]
