# Generated by Django 2.2 on 2019-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0004_auto_20190419_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='dist',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
