# Generated by Django 2.2 on 2019-04-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0005_auto_20190419_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
    ]
