# Generated by Django 2.2 on 2019-04-19 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0006_remove_ingredient_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkbenchApp.Recipe', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientInventory',
        ),
    ]
