# Generated by Django 2.2 on 2019-04-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkbenchApp', '0008_auto_20190419_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
